name: solara
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/Core Packages
  cupertino_icons: ^1.0.2 # iOS style icons
  provider: ^6.1.2 # State management (örneğin tema için kullandık) - Versiyonu sizdekiyle eşleştirin
  flutter_svg: ^2.0.10+1 # SVG desteği - Versiyonu sizdekiyle eşleştirin

  # Feature Packages
  http: ^1.2.1 # HTTP istekleri için - Versiyonu sizdekiyle eşleştirin
  image_picker: ^1.1.0 # Galeri/Kamera erişimi - Versiyonu sizdekiyle eşleştirin
  shared_preferences: ^2.2.3 # Basit veri saklama (tema ayarı için eklendi) - En son versiyonu kullanın
  flutter_secure_storage: ^9.0.0 # Güvenli veri saklama (token için) - En son stabil versiyonu kontrol edin
  timeago: ^3.7.1
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2 # Kod analizi ve lint kuralları - Versiyonu sizdekiyle eşleştirin

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Resimlerinizin bulunduğu klasör

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
